osx_image: xcode11.2
language: objective-c
before_install:
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/CloudInAppMessaging.xcworkspace -scheme CloudInAppMessaging_Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick